# Generated by Django 2.0.6 on 2018-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.URLField(blank=True, default=None),
        ),
    ]
