# Generated by Django 2.0.6 on 2018-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20181103_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
