# Generated by Django 2.0.6 on 2018-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20181103_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
