# Generated by Django 2.0.6 on 2018-11-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20181103_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover',
        ),
    ]
