# Generated by Django 2.0.6 on 2018-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_remove_profile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
