# Generated by Django 2.0.6 on 2018-11-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20181106_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
