# Generated by Django 2.0.6 on 2018-11-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_auto_20181106_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
