# Generated by Django 2.0.6 on 2018-11-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181107_1755'),
        ('profile', '0011_auto_20181106_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_by', to='post.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_by', to='post.Post'),
        ),
    ]
